export default {
  GET_ALL_PRODUCTS: 'get_all_products',
  GET_ALL_PRODUCTS_ERROR: 'get_all_products_error',
  GET_PRODUCT_DETAILS: 'get_product_details',
  GET_PRODUCT_DETAILS_ERROR: 'get_product_details_error',
  CLEAR_PRODUCT_DETAILS: 'clear_product_details',
  ADD_CART_ITEM: 'add_cart_item',
  ADD_CART_ITEM_ERROR: 'add_cart_item',
  GET_CART_ITEMS: 'get_cart_items',
  GET_CART_ITEMS_ERROR: 'get_cart_items_error',
  DELETE_CART_ITEM: 'delete_cart_item',
  DELETE_CART_ITEM_ERROR: 'delete_cart_item_error',
  CLEAR_ERRORS: 'clear_errors',
  SIGN_UP_ERROR: 'sign_up_error',
  SIGN_IN_ERROR: 'sign_in_error',
  SIGN_IN: 'sign_in',
  SIGN_OUT: 'sign_out',
  SIGN_UP: 'sign_up',
};
